### ISSUE TITLE
Multiple Stores FAQ (English and French)

### ISSUE THREAD

**Issue by wsisme** [abdev/magento-FAQ#1]
Hi,

First of all, thank you very much for this free Magento FAQ extension. It works great! My only concern is trying to use this FAQ manager on a bilingual website. I would like to have specific FAQs for my English store view and other FAQs for my French store view. 

Is there a way to do this with your tool?
Thanks!
Dominic

**Comment by abdev** [comment]
Hi Dominic,

Unfortunately it's not possible at this point. I have to make a few changes to add this new feature. If you can wait until Monday, 6 September, then you'll have this feature also.

**Comment by wsisme** [comment]
Thank you. I will wait for your update! :)

**Comment by abdev** [comment]
I've added the multistore view for categories and articles :).

**Comment by abdev** [comment]
P.S: please use my website to download the extension, the github repository is not properly updated (I'll delete it later this week):
http://www.pandawebstudio.com/projects/free-magento-faq-extension

**Comment by wsisme** [comment]
Thank you! :)
